name: rl-medical
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - blas=1.0=mkl
  - ca-certificates=2020.7.22=0
  - certifi=2020.6.20=py38_0
  - cudatoolkit=10.2.89=hfd86e86_1
  - freetype=2.10.2=h5ab3b9f_0
  - intel-openmp=2020.2=254
  - jpeg=9b=h024ee3a_2
  - lcms2=2.11=h396b838_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20191231=h14c3975_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_1
  - lz4-c=1.9.2=he6710b0_1
  - mkl=2020.2=256
  - mkl-service=2.3.0=py38he904b0f_0
  - mkl_fft=1.2.0=py38h23d657b_0
  - mkl_random=1.1.1=py38h0573a6f_0
  - ncurses=6.2=he6710b0_1
  - ninja=1.10.1=py38hfd86e86_0
  - numpy-base=1.19.1=py38hfa32c7d_0
  - olefile=0.46=py_0
  - openssl=1.1.1h=h7b6447c_0
  - pillow=7.2.0=py38hb39fc2d_0
  - pip=20.2.3=py38_0
  - python=3.8.5=h7579374_1
  - pytorch=1.6.0=py3.8_cuda10.2.89_cudnn7.6.5_0
  - readline=8.0=h7b6447c_0
  - setuptools=50.3.0=py38_0
  - six=1.15.0=py_0
  - sqlite=3.33.0=h62c20be_0
  - tk=8.6.10=hbc83047_0
  - torchvision=0.7.0=py38_cu102
  - wheel=0.35.1=py_0
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.5=h9ceee32_0
  - pip:
    - absl-py==0.10.0
    - cachetools==4.1.1
    - chardet==3.0.4
    - cloudpickle==1.6.0
    - future==0.18.2
    - google-auth==1.22.1
    - google-auth-oauthlib==0.4.1
    - grpcio==1.32.0
    - gym==0.17.3
    - idna==2.10
    - markdown==3.2.2
    - numpy==1.19.2
    - oauthlib==3.1.0
    - opencv-python==4.4.0.44
    - protobuf==3.13.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pyglet==1.5.0
    - requests==2.24.0
    - requests-oauthlib==1.3.0
    - rsa==4.6
    - scipy==1.5.2
    - simpleitk==2.0.0
    - tensorboard==2.3.0
    - tensorboard-plugin-wit==1.7.0
    - tqdm==4.50.0
    - urllib3==1.25.10
    - werkzeug==1.0.1
